import sqlite3
import tkinter as tk
from tkinter import messagebox

# Database creation
def create_database():
    conn = sqlite3.connect('feedback.db')
    cursor = conn.cursor()
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS feedback (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            email TEXT NOT NULL,
            feedback TEXT NOT NULL
        )
    ''')
    conn.commit()
    conn.close()

# function that allows the users to submit their name, email address, and feedback
def submit_feedback(name, email, feedback):
    conn = sqlite3.connect('feedback.db')
    cursor = conn.cursor()
    cursor.execute('''
        INSERT INTO feedback (name, email, feedback) VALUES (?, ?, ?)
    ''', (name, email, feedback))
    conn.commit()
    conn.close()
    messagebox.showinfo("Success", "Feedback submitted successfully!")

# function that allows the user to check all of the feedback data generated by the program, given that they have the correct password.
def display_feedback():
    password = input("Enter password to access feedback data: ")
    
    if password == "ilovefish22":
        conn = sqlite3.connect('feedback.db')
        cursor = conn.cursor()
        cursor.execute('SELECT * FROM feedback')
        entries = cursor.fetchall()
        
        for entry in entries:
            print(f"ID: {entry[0]}, Name: {entry[1]}, Email: {entry[2]}, Feedback: {entry[3]}")
        
        conn.close()
    else:
        print("WRONG PASSWORD!!!!")

# GUI creation
def create_gui():
    window = tk.Tk()
    window.title("Customer Feedback")

    tk.Label(window, text="Name").grid(row=0)
    tk.Label(window, text="Email").grid(row=1)
    tk.Label(window, text="Feedback").grid(row=2)

    name_entry = tk.Entry(window)
    email_entry = tk.Entry(window)
    feedback_entry = tk.Entry(window, width=50)

    name_entry.grid(row=0, column=1)
    email_entry.grid(row=1, column=1)
    feedback_entry.grid(row=2, column=1)

    submit_button = tk.Button(window, text="Submit", command=lambda: submit_feedback(name_entry.get(), email_entry.get(), feedback_entry.get()))
    submit_button.grid(row=3, column=1)

    retrieve_button = tk.Button(window, text="Retrieve Feedback", command=lambda: display_feedback())
    retrieve_button.grid(row=4, column=1)

    window.mainloop()
create_database()
create_gui()

